config/routes.rb
Rails.application.routes.draw do
  devise_for :users
 root 'top#index'
  resources :list, only: %i(new create edit update destroy) do
    resources :cards, only: %i(new create show edit update destroy)
  end
 resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
    belongs_to :list
    validates :title,length:{in:1...255}
    validates :memo,length:{maximum:1000}
end

app/models/list.rb
class List < ApplicationRecord
    belongs_to :user
    validates :title, length: { in: 1..255 } 
    has_many :cards,dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :name, presence: true, length: { maximum: 20 }
  validates :email, presence: true
  has_many :lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
    before_action :set_card,only:%i(show edit update destroy)
    def show
        
    end
    
    def new
        @card=Card.new
        @list = List.find_by(id: params[:list_id])
    end
    
    def create
        @card=Card.new(card_params)
        if @card.save
            redirect_to :root
        else
            render action: :new
        end
    end
    
    def edit
        @lists=List.where(user: current_user)
    end
    
    def update
        
        if @card.update_attributes(card_params)
            redirect_to :root
        else
            render action: :edit
        end
    end
    
    def destroy
        @card.destroy
        redirect_to :root
    end
    
    private 
    def card_params
        params.require(:card).permit(:title,:memo,:list_id)
    end
    
    def set_card
        @card=Card.find(params[:id])
    end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
    before_action :set_list, only: %i(edit update destroy)
    def new
        @list=List.new
    end
    
    def create
        @list=List.new(list_params)
         if @list.save
            redirect_to :root
         else
            render action: :new
         end
    end
    
    def edit
       
    end
    
    def update
     
      if @list.update_attributes(list_params)
      redirect_to :root
      else
      render action: :edit
      end
    end
    
    def destroy
        @list.destroy
        redirect_to :root
    end
    
    private
    def list_params
         params.require(:list).permit(:title).merge(user: current_user)
    end
    
    
    def set_list
      @list = List.find(params[:id])
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  
    @lists = List.where(user: current_user).order("created_at ASC")
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @users = User.all
  end

  def show
    @user=User.find(params[:id])
  end

  def edit
    @user=User.find(params[:id])
    if @user != current_user
      redirect_to root_path, alert: '不正なアクセスです。' 
    end
  end
  
  def update
    @user=User.find(params[:id])
    if @user.update(user_params)
       redirect_to root_path,notice: '更新に成功しました'
    else
      render :edit
    end
  end
  
  private #privateでusercontrollerでしか呼び出せなくなる
  def user_params 
    params.require(:user).permit(:name,:email,:profile,:profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/edit.html.erb
<div class="cardeditPgae">
  <div class='container'>
    <%= form_with model: @card, url: { action: :update }, html: { class: 'cardeditForm' }, local: true do |f| %>
      <% if @card.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <div class="cardeditForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control", placeholder: "カード名" %>
      </div>
      <div class="cardeditForm_memo">
        <%= f.label :memo %>
        <%= f.text_area :memo, class: "form-control", placeholder: "詳細" %>
      </div>
      <div class="cardeditForm_memo">
        <lable>リスト名</lable>
        <%=select :card,:list_id,@lists.map{|i|[i.title,i.id]},{},{class:'form-control'} %>
      </div>
      <div class="text-center"><%= f.submit "更新する", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/cards/new.html.erb
<div class="cardnewPgae">
  <div class='container'>
    <%= form_with model: @card, url: { action: :create }, html: { class: 'cardnewForm' }, local: true do |f| %>
      <%= f.hidden_field :list_id, value: @list.id %>
      <% if @card.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <div class="cardnewForm_title">
        <%= f.label :title %>
        <%= f.text_field :title, autofocus: true, class: "form-control", placeholder: "カード名" %>
      </div>
      <div class="cardnewForm_memo">
        <%= f.label :memo %>
        <%= f.text_area :memo, autofocus: true, class: "form-control", placeholder: "詳細" %>
      <div class="text-center"><%= f.submit "作成する", class: "submitBtn" %></div>
      </div>
    <% end %>
  </div>
</div>

app/views/cards/show.html.erb
<div class='carddetailPage'>
  <div class="container">
    <div class="cardContents">
      <div class="cardContents_title">
        <div>タイトル</div>
        <h2><%= @card.title %></h2>
      </div>
      <div class="cardContents_memo">
        <div>メモ</div>
        <div><%= @card.memo %></div>
      </div>
      <div class="cardContents_listStatus">
        <div>リスト名</div>
        <div><%= @card.list.title %></div>
      </div>
      
       <div class="cardContents_btnArea">
        <%= link_to '編集する', edit_list_card_path(@card.list, @card), class: "edit_btn" %>
        <%=link_to '削除する',list_card_path(@card.list,@card),class:"text-danger delete_btn",method: :delete,data:{confirm:"このカードを削除して大丈夫ですか？"} %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kanban</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%=render 'partial/header' if current_user%>
   
     <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/list/edit.html.erb
<div class="listeditPage">
  <div class="container">
    <%= form_with model: @list, url: { action: :update }, html: { class: 'listForm' }, local: true do |f| %>
      <% if @list.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control listName", placeholder: "リスト名" %>
      <div class="text-center"><%= f.submit "編集する", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/list/new.html.erb
<div class="listnewPage">
  <div class="container">
    <%= form_with model: @list, url: { action: :create }, class: "new_list", local: true do |f| %>
      <% if @list.errors.any? %>
        <p class="text-danger">タイトルは1～255文字以内で入力してください</p>
      <% end %>
      <%= f.label :title %>
      <%= f.text_field :title, autofocus: true, class: "form-control listName", placeholder: "リスト名" %>
      <div class="text-center"><%= f.submit "作成", class: "submitBtn" %></div>
    <% end %>
  </div>
</div>

app/views/partial/_header.html.erb
<header class="header">
      <nav class="nav">
        <ul class="header_menu">
          <%=link_to  edit_user_path(current_user) do %>
           <li class="nav-link"><%=current_user.name%>さん</li>
          <%end%>
          <li class="header_menu_title"><%= link_to "kanban", root_path, class: "nav-link" %></li>
          <li>
            <ul class="header_menu_inner">
              <%# リストを作成するリンクは今後開発していくので、今は"#"にしておきます。 %>
              <li>
                <%= link_to new_list_path, class: "nav-link" do %>
                  <span class="mr-1">リストを作成</span>
                  <i class="fas fa-edit"></i>
                <% end %>
              </li>
              <li><%= link_to "サインアウト",destroy_user_session_path, class: "nav-link",method: :delete %></li>
            </ul>
          </li>
        </ul>
      </nav>
</header>

app/views/top/index.html.erb
<div class="topPage">
  <div class="listWrapper">
    <% @lists.each do |list| %>
      <div class="list">
        <div class="list_header">
          <h2 class="list_header_title"><%= list.title %></h2>
          <div class="list_header_action">
            <%= link_to content_tag(:i, '', class: 'fas fa-trash'), list, method: :delete, data: { confirm: "#{list.title}を削除して大丈夫ですか？" } %>
            <%= link_to(content_tag(:i, '', class: 'fas fa-pen'), edit_list_path(list)) %>
          </div>
        </div>

        <div class="cardWrapper">

         
          <% list.cards.each do |card| %>
          <%=link_to list_card_path(list,card),class:"cardDatail_link" do%>
            <div class="card">
              <h3 class="card_title"><%= card.title %></h3>
              <% if card.memo.size > 0 %>
                <div class="card_detail is-exist"><i class="fas fa-bars"></i></div>
              <% end %>
            </div>
          <% end %>
         
          <%end%>

          <div class="addCard">
            <i class="far fa-plus-square"></i>
            <%= link_to "さらにカードを追加", new_list_card_path(list), class: "addCard_link" %>
          </div>
          
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        ユーザー編集
      </h1>
    </div>
  </div>
</section>


<% if @user.errors.any? %>
  <div class="notification is-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-6">
        <%= form_for @user do |f| %>
            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, class: "form-control", placeholder: "名前を入力してください" %>
              </div>

            <div class="form-group">
               <%= f.label :email %>
              <%= f.email_field :email, class: "form-control", placeholder: "emailを入力してください" ,autocomplete: "email" %>
            </div>
          

          <%= f.submit "更新", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>